# Generated by Django 5.2 on 2025-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('razsoc', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('checkin', models.CharField(blank=True, max_length=1, null=True)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CLIENTE_CONVIDADO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteQtd',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('qtd_convites', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': True,
            },
        ),
    ]
