# Generated by Django 5.2 on 2025-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteqtd',
            name='razsoc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
