# Generated by Django 5.2 on 2025-04-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0002_clienteqtd_razsoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteqtd',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
