# Generated by Django 5.2 on 2025-04-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0003_clienteqtd_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteqtd',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
